"""Initial commit

Revision ID: 4b2c7c9afdde
Revises: 
Create Date: 2026-08-28 13:23:04.403055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2c7c9afdde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ligne',
    sa.Column('ligne_id', sa.Text(), nullable=False),
    sa.Column('ligne_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('ligne_nsv_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ligne_id', 'ligne_time')
    )
    op.create_table('new_ligne_data',
    sa.Column('ligne_id', sa.Text(), nullable=False),
    sa.Column('ligne_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('ligne_nsv_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ligne_id', 'ligne_time')
    )
    op.create_table('new_trr_data',
    sa.Column('trr_id', sa.Text(), nullable=False),
    sa.Column('trr_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('trr_nsv_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('trr_id', 'trr_time')
    )
    op.create_table('trr',
    sa.Column('trr_id', sa.Text(), nullable=False),
    sa.Column('trr_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('trr_nsv_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('trr_id', 'trr_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trr')
    op.drop_table('new_trr_data')
    op.drop_table('new_ligne_data')
    op.drop_table('ligne')
    # ### end Alembic commands ###
