"""remove buffer tables

Revision ID: 6e3dede66d20
Revises: 4b2c7c9afdde
Create Date: 2026-09-04 20:49:44.251426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e3dede66d20'
down_revision: Union[str, Sequence[str], None] = '4b2c7c9afdde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_ligne_data')
    op.drop_table('new_trr_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_trr_data',
    sa.Column('trr_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trr_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('trr_nsv_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('trr_id', 'trr_time', name=op.f('new_trr_data_pkey'))
    )
    op.create_table('new_ligne_data',
    sa.Column('ligne_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ligne_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ligne_nsv_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ligne_id', 'ligne_time', name=op.f('new_ligne_data_pkey'))
    )
    # ### end Alembic commands ###
