"""add OpenMeteo table

Revision ID: a363ce673a02
Revises: 6e3dede66d20
Create Date: 2026-09-07 13:21:58.173694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a363ce673a02'
down_revision: Union[str, Sequence[str], None] = '6e3dede66d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openmeteo',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=False),
    sa.Column('apparent_temperature', sa.Float(), nullable=False),
    sa.Column('relativehumidity_2m', sa.Integer(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('rain', sa.Float(), nullable=False),
    sa.Column('snowfall', sa.Float(), nullable=False),
    sa.Column('weathercode', sa.Integer(), nullable=False),
    sa.Column('pressure_msl', sa.Float(), nullable=False),
    sa.Column('cloudcover', sa.Integer(), nullable=False),
    sa.Column('windspeed_10m', sa.Float(), nullable=False),
    sa.Column('windgusts_10m', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openmeteo')
    # ### end Alembic commands ###
