"""add HourlyAggregate table

Revision ID: d76edb7ef91f
Revises: e88f0d09a9ae
Create Date: 2026-09-25 13:20:02.086345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76edb7ef91f'
down_revision: Union[str, Sequence[str], None] = 'e88f0d09a9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_hourly_aggregates',
    sa.Column('hour_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('traffic_type', sa.Text(), nullable=False),
    sa.Column('average_congestion_level', sa.Float(), nullable=False),
    sa.Column('pollution_index', sa.Float(), nullable=False),
    sa.Column('pm10_index', sa.Float(), nullable=False),
    sa.Column('pm2_5_index', sa.Float(), nullable=False),
    sa.Column('o3_index', sa.Float(), nullable=False),
    sa.Column('no2_index', sa.Float(), nullable=False),
    sa.Column('so2_index', sa.Float(), nullable=False),
    sa.Column('precipitation_total', sa.Float(), nullable=False),
    sa.Column('rainfall_total', sa.Float(), nullable=False),
    sa.Column('average_temperature', sa.Float(), nullable=False),
    sa.Column('average_relative_humidity', sa.Float(), nullable=False),
    sa.Column('average_cloud_cover', sa.Float(), nullable=False),
    sa.Column('average_wind_speed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('hour_start', 'traffic_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_hourly_aggregates')
    # ### end Alembic commands ###
