"""add Atmo table

Revision ID: e88f0d09a9ae
Revises: a363ce673a02
Create Date: 2026-09-11 12:37:38.233341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88f0d09a9ae'
down_revision: Union[str, Sequence[str], None] = 'a363ce673a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atmo',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pollution_index', sa.Integer(), nullable=False),
    sa.Column('is_value_mesured', sa.Boolean(), nullable=False),
    sa.Column('PM10_index', sa.Integer(), nullable=False),
    sa.Column('PM2_5_index', sa.Integer(), nullable=False),
    sa.Column('O3_index', sa.Integer(), nullable=False),
    sa.Column('NO2_index', sa.Integer(), nullable=False),
    sa.Column('SO2_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atmo')
    # ### end Alembic commands ###
