POSTGRES_USER=app
POSTGRES_PASSWORD=$(tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 32)
POSTGRES_PORT=5433
POSTGRES_DB=api_db

echo "POSTGRES_USER=$POSTGRES_USER" > .env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
echo "POSTGRES_DB=$POSTGRES_DB" >> .env

POSTGRES_TEST_USER=test
POSTGRES_TEST_PASSWORD=$(tr -dc 'A-Za-z0-9!?%=' < /dev/urandom | head -c 32)
POSTGRES_TEST_PORT=54320
POSTGRES_TEST_DB=test_db

echo "POSTGRES_TEST_USER=$POSTGRES_TEST_USER" >> .env
echo "POSTGRES_TEST_PASSWORD=$POSTGRES_TEST_PASSWORD" >> .env
echo "POSTGRES_TEST_PORT=$POSTGRES_TEST_PORT" >> .env
echo "POSTGRES_TEST_DB=$POSTGRES_TEST_DB" >> .env