# Db variables
POSTGRES_USER=app
POSTGRES_PASSWORD=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)
POSTGRES_HOST=localhost
POSTGRES_PORT=5433
POSTGRES_DB=api_db
DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@db/$POSTGRES_DB
echo "POSTGRES_USER=$POSTGRES_USER" > .env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
echo "POSTGRES_DB=$POSTGRES_DB" >> .env
echo "DATABASE__SQL_ALCHEMY_CONN=$DATABASE__SQL_ALCHEMY_CONN" >> .env
export POSTGRES_USER
export POSTGRES_PASSWORD
export POSTGRES_PORT
export POSTGRES_HOST
export POSTGRES_DB
export DATABASE__SQL_ALCHEMY_CONN

# Test db variables
POSTGRES_TEST_USER=test
POSTGRES_TEST_PASSWORD=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)
POSTGRES_TEST_PORT=54320
POSTGRES_TEST_HOST=localhost
POSTGRES_TEST_DB=test_db
TEST__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://$POSTGRES_TEST_USER:$POSTGRES_TEST_PASSWORD@test_db/$POSTGRES_TEST_DB
echo "POSTGRES_TEST_USER=$POSTGRES_TEST_USER" >> .env
echo "POSTGRES_TEST_PASSWORD=$POSTGRES_TEST_PASSWORD" >> .env
echo "POSTGRES_TEST_PORT=$POSTGRES_TEST_PORT" >> .env
echo "POSTGRES_TEST_HOST=$POSTGRES_TEST_HOST" >> .env
echo "POSTGRES_TEST_DB=$POSTGRES_TEST_DB" >> .env
echo "TEST__DATABASE__SQL_ALCHEMY_CONN=$TEST__DATABASE__SQL_ALCHEMY_CONN" >> .env
export POSTGRES_TEST_USER
export POSTGRES_TEST_PASSWORD
export POSTGRES_TEST_PORT
export POSTGRES_TEST_HOST
export POSTGRES_TEST_DB
export TEST__DATABASE__SQL_ALCHEMY_CONN

# Airflow variables
AIRFLOW_USER=airflow
AIRFLOW_PASSWORD=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)
AIRFLOW_DB=airflow
AIRFLOW_PORT=8081
AIRFLOW_PROJ_DIR=./airflow
ENV_FILE_PATH=".env"
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql+psycopg2://$AIRFLOW_USER:$AIRFLOW_PASSWORD@airflow_metadata_db/$AIRFLOW_DB"
AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://$AIRFLOW_USER:$AIRFLOW_PASSWORD@airflow_metadata_db/$AIRFLOW_DB
AIRFLOW_IMAGE_NAME="tutorial-mtram-based-airflow:latest"
FERNET_KEY=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 264)
AIRFLOW__API_AUTH__JWT_SECRET=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 264)
AIRFLOW__API_AUTH__JWT_ISSUER=airflow_$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 16)
_AIRFLOW_WWW_USER_USERNAME=airflow_$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 16)
_AIRFLOW_WWW_USER_PASSWORD=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)
echo "AIRFLOW_UID=$(id -u)" >> .env
echo "AIRFLOW_USER=$AIRFLOW_USER" >> .env
echo "AIRFLOW_PASSWORD=$AIRFLOW_PASSWORD" >> .env
echo "AIRFLOW_DB=$AIRFLOW_DB" >> .env
echo "AIRFLOW_PORT=$AIRFLOW_PORT" >> .env
echo "AIRFLOW_PROJ_DIR=$AIRFLOW_PROJ_DIR" >> .env
echo "ENV_FILE_PATH=$ENV_FILE_PATH" >> .env
echo "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=$AIRFLOW__DATABASE__SQL_ALCHEMY_CONN" >> .env
echo "AIRFLOW__CELERY__RESULT_BACKEND=$AIRFLOW__CELERY__RESULT_BACKEND" >> .env
echo "AIRFLOW_IMAGE_NAME=$AIRFLOW_IMAGE_NAME" >> .env
echo "FERNET_KEY=$FERNET_KEY" >> .env
echo "AIRFLOW__API_AUTH__JWT_SECRET=$AIRFLOW__API_AUTH__JWT_SECRET" >> .env
echo "AIRFLOW__API_AUTH__JWT_ISSUER=$AIRFLOW__API_AUTH__JWT_ISSUER" >> .env
echo "_AIRFLOW_WWW_USER_USERNAME=$_AIRFLOW_WWW_USER_USERNAME" >> .env
echo "_AIRFLOW_WWW_USER_PASSWORD=$_AIRFLOW_WWW_USER_PASSWORD" >> .env
export AIRFLOW_USER
export AIRFLOW_PASSWORD
export AIRFLOW_DB
export AIRFLOW_PORT
export AIRFLOW_PROJ_DIR
export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
export AIRFLOW__CELERY__RESULT_BACKEND
export AIRFLOW_IMAGE_NAME
export FERNET_KEY
export AIRFLOW__API_AUTH__JWT_SECRET
export AIRFLOW__API_AUTH__JWT_ISSUER
export _AIRFLOW_WWW_USER_USERNAME
export _AIRFLOW_WWW_USER_PASSWORD