name: Python tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12.3' 
      - run: |
          source scripts/dev/setup.sh
          pytest
          pytest tests/etl_integration_test.py