name: Python tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
      - run: pip3 install -r requirements/dev.txt
      - run: |
          source scripts/setup.sh
          pytest
          pytest tests/etl_integration_test.py